name: CI - Cypress Tests with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run Cypress component tests with coverage
      - name: Run component tests (with coverage)
        run: npm run test:component:coverage

      # 5. Run Cypress e2e tests with coverage
      - name: Run e2e tests (with coverage)
        run: npm run test:e2e:coverage:noerror

      
